<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="Initialization\InitialData.json" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tenisu.Infrastructure.Tests" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tenisu.Domain\Tenisu.Domain.csproj" />
  </ItemGroup>
</Project>
